- name: set empty stdout_lines list
  set_fact:
    stdout_lines: []

- name: Test if api-int OpenShift Entries Exist
  command: "dig +short @{{ idm_server_ip }} api-int.{{ cluster_name }}.{{ idm_dns_forward_zone }}"
  register: validate_entry
  changed_when: false

- name: update stdout_lines list with api-int check result
  set_fact:
    stdout_lines: "{{ stdout_lines + validate_entry.stdout_lines }}"

- name: Test if api OpenShift Entries Exist
  command: "dig +short @{{ idm_server_ip }} api.{{ cluster_name }}.{{ idm_dns_forward_zone }}"
  changed_when: false
  register: validate_entry

- name: update stdout_lines list with api check result
  set_fact:
    stdout_lines: "{{ stdout_lines + validate_entry.stdout_lines }}"

- name: Test if application endpoint for OpenShift  Exist
  command: "dig +short @{{ idm_server_ip }} test.apps.{{ cluster_name }}.{{ idm_dns_forward_zone }}"
  register: validate_entry
  changed_when: false

- name: update stdout_lines list with cluster end point
  set_fact:
    stdout_lines: "{{ stdout_lines + validate_entry.stdout_lines }}"

- name: show validate entry
  debug:
    var: validate_entry
    verbosity: 2



