- name: check if localstorage operator is already deployed
  shell: /usr/local/bin/oc get all -n local-storage
  register: local_storage_status
  ignore_errors: yes
  changed_when: False
  environment:
    KUBECONFIG: "{{ openshift_install_dir }}/auth/kubeconfig"

- set_fact:
    operator_deployed: yes
    
- name: set the local storage operator status
  set_fact:
    operator_deployed: no
  when: "'No resources found in local-storage namespace' in local_storage_status.stderr"

- name: deploy the localstorage operator
  block:
    - name: Copying over localstorage operator template
      template:
        src: templates/localstorage-operator.yaml.j2
        dest:  "{{ openshift_install_dir }}/localstorage-operator.yaml"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: 0666
    
    - name: Create and Subscribe to the local-storage Catalog
      command: "/usr/local/bin/oc apply -f {{ openshift_install_dir }}/localstorage-operator.yaml"
      environment:
        KUBECONFIG: "{{ openshift_install_dir }}/auth/kubeconfig"
    
    - name: list all libvirt vms
      virt:
        command: list_vms
      register: all_vms
      tags: [ deploy_nodes, rhcos, bootstrap ]
    
    - name: initialize and empty list of all the ocp4 nodes
      set_fact:
        ocp4_compute_nodes: [ '' ]
      tags: [ deploy_nodes, rhcos ]
    
    - name: add compute nodes to ocp4 nodes list
      vars:
        vm_name: "compute-{{ '%00x' |format(item) }}"
      set_fact:
        ocp4_compute_nodes: "{{ ocp4_compute_nodes + [ vm_name ] }}"
      loop: "{{ range(0, compute_count|int)|list }}"
    
    - name: Copying over localstorage customer resource filesystem template
      template:
        src: templates/localstorage-filesystem.yaml.j2
        dest:  "{{ openshift_install_dir }}/localstorage-filesystem.yaml"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: 0666
      when: localstorage_filesystem
    
    - name: Provision the localstroage custom resource type filesystem
      command: "/usr/local/bin/oc create -f {{ openshift_install_dir }}/localstorage-filesystem.yaml"
      environment:
        KUBECONFIG: "{{ openshift_install_dir }}/auth/kubeconfig"
      when: localstorage_filesystem
    
    - name: Copying over localstorage custom resource block template
      template:
        src: templates/localstorage-block.yaml.j2
        dest:  "{{ openshift_install_dir }}/localstorage-block.yaml"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: 0666
      when: localstorage_block
    
    - name: Provision the localstorage custom resource block storage
      command: "/usr/local/bin/oc create -f {{ openshift_install_dir }}/localstorage-block.yaml"
      environment:
        KUBECONFIG: "{{ openshift_install_dir }}/auth/kubeconfig"
      when: localstorage_block
  when: not operator_deployed

#- name: Remove the local volumes for filesystem
#  command: "/usr/local/bin/oc delete -f {{ openshift_install_dir }}/localstorage-filesystem.yaml"
#  environment:
#    KUBECONFIG: "{{ openshift_install_dir }}/auth/kubeconfig"

#- name: Remove the local volumes for block
#  command: "/usr/local/bin/oc delete -f {{ openshift_install_dir }}/localstorage-block.yaml"
#  environment:
#    KUBECONFIG: "{{ openshift_install_dir }}/auth/kubeconfig"
#
#- name: Remove  local storage project and operator
#  command: "/usr/local/bin/oc delete -f {{ openshift_install_dir }}/localstorage-operator.yaml"
#  environment:
#    KUBECONFIG: "{{ openshift_install_dir }}/auth/kubeconfig"
#  ignore_errors: yes
#  when: tear_down  | bool
