---
- name: check local-storage
  include: configure-local-storage-checks.yml

- name: deploy the localstorage operator
  block:
    - name: Copying over localstorage operator template
      template:
        src: templates/localstorage-operator.yaml.j2
        dest:  "{{ openshift_install_dir }}/localstorage-operator.yaml"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
        mode: 0666

    - name: Create and Subscribe to the local-storage Catalog
      command: "/usr/local/bin/oc apply -f {{ openshift_install_dir }}/localstorage-operator.yaml"
      environment:
        KUBECONFIG: "{{ openshift_install_dir }}/auth/kubeconfig"

    - name: wait for local-storage pods
      command: oc -n local-storage get pods
      register: local_storage_pod_out
      retries: 5
      delay: 1
      until: local_storage_pod_out.stdout.find("Running") != -1
      environment:
        KUBECONFIG: "{{ openshift_install_dir }}/auth/kubeconfig"
  when: not namespace_exist and not local_storage_operator_exist

- name: check local-storage
  include: configure-local-storage-checks.yml

- name: list all libvirt vms
  virt:
    command: list_vms
  changed_when: False
  register: all_vms
  tags: [ deploy_nodes, rhcos, bootstrap, localstorage ]


- name: initialize and empty list of all the ocp4 nodes
  set_fact:
    ocp4_compute_nodes: [ '' ]
  tags: [ deploy_nodes, rhcos, localstorage ]

- name: add compute nodes to ocp4 nodes list
  vars:
    vm_name: "compute-{{ '%00x' |format(item) }}"
  set_fact:
    ocp4_compute_nodes: "{{ ocp4_compute_nodes + [ vm_name ] }}"
  loop: "{{ range(0, compute_count|int)|list }}"

- name: provision local volumes
  block:
    - name: create a filesystem local volume resource
      block:
        - name: Copying over localstorage customer resource filesystem template
          template:
            src: templates/localstorage-filesystem.yaml.j2
            dest:  "{{ openshift_install_dir }}/localstorage-filesystem.yaml"
            owner: "{{ admin_user }}"
            group: "{{ admin_user }}"
            mode: 0666
    
        - name: Provision the localstroage custom resource type filesystem
          command: "/usr/local/bin/oc create -f {{ openshift_install_dir }}/localstorage-filesystem.yaml"
          environment:
            KUBECONFIG: "{{ openshift_install_dir }}/auth/kubeconfig"
      when: localstorage_filesystem and localvol_filesystem_sc.rc != 0

    - name: create a block local volume resource
      block:
        - name: Copying over localstorage custom resource block template
          template:
            src: templates/localstorage-block.yaml.j2
            dest:  "{{ openshift_install_dir }}/localstorage-block.yaml"
            owner: "{{ admin_user }}"
            group: "{{ admin_user }}"
            mode: 0666
          when: localstorage_block
    
        - name: Provision the localstorage custom resource block storage
          command: "/usr/local/bin/oc create -f {{ openshift_install_dir }}/localstorage-block.yaml"
          environment:
            KUBECONFIG: "{{ openshift_install_dir }}/auth/kubeconfig"
      when: localstorage_block and localvol_block_sc.rc != 0
  when: namespace_exist and local_storage_operator_exist
