---
- name: enable required firewall ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop: "{{ ocp4_firewall_ports }}"
  register: enable_firewall_ports
  tags: firewall

- name: Allow NFS traffic from VM's to Host
  firewalld:
    zone: libvirt
    state: enabled
    permanent: yes
    service: "{{ item }}"
  with_items:
    - nfs
    - mountd
    - rpc-bind
  register: enable_nfs_ports
  notify: 'reload firewalld'
  tags: firewall

- name: Allow OpenShift traffic from VM's to Host
  firewalld:
    zone: libvirt
    state: enabled
    permanent: yes
    port: "{{ item }}"
  with_items:
    - 80/tcp
    - 443/tcp
    - 6443/tcp
    - 22623/tcp
  notify: 'reload firewalld'
  register: allow_vm_traffic
  tags: firewall

- name: Allow OpenShift traffic from public to Host
  firewalld:
    zone: public
    state: enabled
    permanent: yes
    port: "{{ item }}"
  with_items:
    - 80/tcp
    - 443/tcp
    - 6443/tcp
    - 8080/tcp
  notify: 'reload firewalld'
  tags: firewall
  register: allow_traffic

- name: reload firewalld
  command: 'firewall-cmd --reload'
  tags: [ deploy_nodes, rhcos, node_profile, add_computes ]
  when:
    - allow_traffic.changed or allow_vm_traffic.changed or enable_nfs_ports.changed or enable_firewall_ports.changed
