---
- name: Get a list of running vms
  shell: |
    if virsh list --state-running | grep -q {{ hostname_prefix }}
    then
        echo "Running"
    else
        echo "NotRunning"
    fi
  register: active_vms
  tags: generate_inventory

- name: Build list of cluster node types
  when: active_vms.stdout == 'Running'
  block:
    - name: getting all ocp4 nodes
      shell: oc get nodes -o wide --no-headers=true | awk '{print $1,$6,$3}'
      register: all_ocp_nodes
      ignore_errors: yes
      changed_when: False
      become: no
      tags: generate_inventory
    
    - name: getting compute nodes
      shell: oc get nodes -o wide --no-headers=true | awk '/compute/ {print $1,$6,$3}'
      register: compute_ocp4_nodes
      ignore_errors: yes
      changed_when: False
      when: all_ocp_nodes and all_ocp_nodes.rc == 0
      become: no
      tags: generate_inventory
    
    - name: getting control nodes
      shell: oc get nodes -o wide --no-headers=true | awk '/ctrlplane/ {print $1,$6,$3}'
      register: control_ocp4_nodes
      ignore_errors: yes
      when: all_ocp_nodes and all_ocp_nodes.rc == 0
      changed_when: False
      become: no
      tags: generate_inventory
    
    - name: create/update ocp4 nodes ansible inventory
      template:
        src: ocp4-nodes-inventory.yml
        dest: "{{ project_dir }}/inventory/ocp4-nodes"
        owner: "{{ admin_user }}"
        group: "{{ admin_user }}"
      tags: generate_inventory
