---
# tasks file for ocp4-kvm-deployer
- name: import tasks pre_tasks.yml
  import_tasks: pre_tasks.yml

- name: check if cluster is deployed and report state of cluster
  import_tasks: check_cluster.yml
  when: not tear_down|bool

- name: import tasks tear_down.yml
  import_tasks: tear_down.yml
  when: tear_down|bool

- name: import task deploy.yml
  import_tasks: deploy.yml
  when: not tear_down|bool and cluster_status == 'not deployed'

- name: import task post_install.yml
  import_tasks: post_install.yml
  when: not tear_down|bool and cluster_status == 'not deployed'

- name: import startup task
  import_tasks: startup.yml
  when: not tear_down|bool and startup_cluster|bool
