---
- name: Get API for command line
  command: oc whoami --show-server
  register: showserver
  tags: smoketest
  become: no

- name: Ensure web console is known
  when: webconsole is not defined
  block:
    - name: Get console route
      command: oc get route -n openshift-console console -o json
      register: routeconsole
      retries: 10
      delay: 30
      until: routeconsole is succeeded
      ignore_errors: true

    - name: Set webconsole address
      set_fact:
        webconsole: "http://{{ routeconsole.stdout | from_json | json_query('spec.host') }}"
      when: routeconsole is succeeded
  tags: smoketest
  become: no

- name: verify dns and cluster
  block:
    - name: Check DNS webconsole
      command: nslookup "{{ webconsole | urlsplit('hostname') }}"
      register: checkdnswebconsole
      changed_when: false
      retries: 15
      until: checkdnswebconsole is succeeded
      delay: 30
      tags: smoketest
      become: no

    - name: Check DNS API
      command: nslookup "{{ showserver.stdout | trim | urlsplit('hostname') }}"
      register: checkdnsapi
      changed_when: false
      tags: smoketest
      become: no

    - name: Webconsole
      uri:
        url: "{{ webconsole }}"
        validate_certs: false
      register: testwebconsole
      retries: 5
      until: testwebconsole is succeeded
      delay: 60
      tags: smoketest
      become: no

    - name: Cluster-info
      command: oc cluster-info
      register: clusterinfor
      changed_when: false
      tags: smoketest
      become: no

- name: test deploying a PHP LAMP Stack
  tags: smoketest
  block:

    - name: Create project
      command: oc new-project postflightcheck
      register: newproject
      tags: smoketest
      become: no

    - name: New-app
      command: oc new-app cakephp-mysql-persistent -n postflightcheck
      register: newapp
      tags: smoketest
      become: no

    - name: Wait for mysql
      command: timeout 600 oc rollout status dc/mysql -w -n postflightcheck
      register: mysqlw
      changed_when: false
      tags: smoketest
      become: no

    - name: Wait for php
      command: timeout 600 oc rollout status dc/cakephp-mysql-persistent -w -n postflightcheck
      register: phpw
      changed_when: false
      retries: 2
      delay: 60
      until: phpw is succeeded
      when: mysqlw.rc != 0
      tags: smoketest
      become: no

    - name: Get route
      command: >-
        oc get route
        -l template=cakephp-mysql-persistent
        --no-headers
        -o json
        -n postflightcheck
      register: getroute
      changed_when: false
      retries: 10
      delay: 5
      until: getroute is succeeded
      tags: smoketest
      become: no
      when: mysqlw.rc != 0

    - name: Test that route is reachable
      uri:
        url: "http://{{ getroute.stdout|from_json|json_query('items[0].spec.host') }}"
      register: testroute
      retries: 15
      delay: 5
      until: testroute is succeeded
      tags: smoketest
      become: no

    - debug:
        msg: "{{ item }}"
      loop:
      - "user.info: "
      - "user.info: Post Flight Check"
      - "user.info: DNS Web Console ............... {{ 'OK' if checkdnswebconsole.rc == 0 else 'FAIL' }}"
      - "user.info: DNS API ....................... {{ 'OK' if checkdnsapi.rc == 0 else 'FAIL' }}"
      - "user.info: Web console ................... {{ 'OK' if testwebconsole is succeeded else 'FAIL' }}"
      - "user.info: API ........................... {{ 'OK' if clusterinfor.rc == 0 else 'FAIL' }}"
      - "user.info: Create Project with PV ........ {{ 'OK' if newproject.rc == 0 else 'FAIL' }}"
      - "user.info: App deployed .................. {{ 'OK' if phpw.rc == 0 and mysqlw.rc == 0 else 'FAIL' }}"
      - "user.info: Route ......................... {{ 'OK' if testroute is succeeded else 'FAIL' }}"
      tags: smoketest
      become: no

  rescue:
    - debug:
        msg: 'Aborting smoke test as a result of a failure when deploying the php lamp stack'
  always:
    - name: Delete project
      command: oc delete project postflightcheck
      tags: smoketest
      become: no
      ignore_errors: yes

    - name: Switch back to default project
      command: oc project default
      tags: smoketest
      become: no
      ignore_errors: yes
