---
# handlers file for ocp4-rhcos-vms
- name: restart nfs
  service:
    name: nfs-server
    state: restarted
  tags: [ deploy_nodes, rhcos, node_profile, add_computes ]

- name: reload firewalld
  command: 'firewall-cmd --reload'
  tags: [ deploy_nodes, rhcos, node_profile, add_computes ]

- name: restart webserver
  service:
    name: qbn-httpd.service
    state: restarted
  tags: [ deploy_nodes, rhcos, node_profile, add_computes ]

- name: restart load balancer
  service:
    name: qbn-lb.service
    state: restarted
  tags: [ deploy_nodes, rhcos, node_profile, add_computes ]
